#!/bin/sh

# configctl - control config setup and installation

# Usage: ./configctl
# Targets POSIX-compliant shells - no less, and no more.

# TODO:
# Handle existing installations

# Variable definitions

BASIC=".bash_aliases .bash_logout .bash_profile .bashrc .byobu .emacs .gitconfig .gitignore .gitmodules .profile .reportbugrc .screenrc .selected_editor .zsh_favlist .zshrc.pre-oh-my-zsh bin .pam_environment .netscape .hgrc .zshrc .zprofile"
HARDLINKS=".pgpkey"
ZSH_PRECOMPILE=".zshrc .zprofile antigen/antigen.zsh .oh-my-zsh/lib/*.zsh .oh-my-zsh/themes/*.zsh-theme .oh-my-zsh/plugins/*/*.zsh .oh-my-zsh/oh-my-zsh.sh"
DIRS=".gnupg .ssh .aptitude .config"
LINK_DIRS=".config/awesome .config/cower .config/terminator"
AFTER_DIRS=".gnupg/gpg.conf .ssh/config .aptitude/config"
TOUCH_FILES=".fetchmail.log"
CONFIG_DIR=$(pwd)
TARGET_DIR=~/configstest

loginfo() {
	echo "[\033[36minfo\033[0m] $1"
}

logwarn() {
	echo "[\033[33mwarn\033[0m] $1"
}

loginfo "Detected configuration directory as $CONFIG_DIR."
loginfo "Using target directory $TARGET_DIR."

# Error checking on target directory
if ! [ -e $TARGET_DIR ]; then
	logwarn "Target directory does not exist."
	loginfo "Creating target directory $TARGET_DIR."
	mkdir -p $TARGET_DIR
	# TODO handle errors
elif ! [ -d $TARGET_DIR ]; then
	echo "[\033[31mfail\033[0m] Fatal error: $TARGET_DIR is not a directory."
	exit 1
fi

# Detect zsh
if command -v zsh 2>&1 >/dev/null; then
	loginfo "Detected $(type zsh | sed 's/is/as/')."
else
	logwarn "Failed to detect zsh. Precompilation will not occur."
fi

loginfo "Installing symlinks..."
for i in $BASIC; do
	printf "Installing $i..."
	ln -s $CONFIG_DIR/$i $TARGET_DIR
	printf " done.\n"
done
loginfo "Done installing symlinks."

loginfo "Installing hardlinks..."
for i in $HARDLINKS; do
	printf "Installing $i..."
	ln $CONFIG_DIR/$i $TARGET_DIR
	printf " done.\n"
done
loginfo "Done installing hardlinks."

loginfo "Creating configuration directories..."
for i in $DIRS; do
	printf "Creating $i..."
	mkdir -p $DIRS
	printf " done.\n"
done
loginfo "Done creating configuration directories."

loginfo "Installing configuration directory symlinks..."
logwarn "Installing configuration directory symlinks is unimplemented."
loginfo "Done installing configuration directory symlinks."

loginfo "Installing symlinks nested in a directory..."
logwarn "Installing symlinks nested in a directory is unimplemented."
loginfo "Done installing symlinks nested in a directory."

loginfo "Touching files..."
for i in $TOUCH_FILES; do
	printf "Touching $i..."
	touch $TARGET_DIR/$i
	printf " done.\n"
done
loginfo "Done touching files."

loginfo "Cloning resources from git..."
# TODO: handle errors
# TODO: print logs for each clone operation
git clone 'git://github.com/robbyrussell/oh-my-zsh' $TARGET_DIR/.oh-my-zsh
git clone 'git://github.com/zsh-users/antigen.git' $TARGET_DIR/antigen
loginfo "Done cloning resources from git."

loginfo "Handling submodules..."
git submodule update --init
loginfo "Done handling submodules."

loginfo "Precompiling zsh scripts..."
cd $TARGET_DIR
for i in $ZSH_PRECOMPILE; do
	printf "Precompiling $i..."
	zsh -c "zcompile $i"
	printf " done.\n"
done
cd -
loginfo "Done precompiling zsh scripts."
